### ISSUE TITLE
Need more instructions to setup

### ISSUE THREAD

**Issue by k0105** [informatics-lab/s3-fuse-flex-volume#1]
Hello,

I'm trying to use this driver, but am not sure how to

a) Define my credentials and bucket.
b) Use it in Minikube.
c) Add custom parameters so I can use it with other S3-compliant storage services besides AWS, e.g. by adding the `--endpoint` parameter.

Could you elaborate on those three topics? I would highly appreciate that. I can already successfully mount my volume with `goofys` itself, so I only need to achieve the same with your driver inside Minikube.

Thank you in advance.

Best wishes,
k0105

**Comment by jacobtomlinson** [comment]
I'm glad you think this will be useful to you! This driver is currently very specific to our setup, but I'm keen to make it more generic. So these answers may not be helpful right now.

a) We are running this on AWS and the credentials are picked up from the [instance role](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html). I would be keen to add config options to specify keys. Not sure what you mean by define bucket?
b) I would need to know more about what operating system minikube runs within the VM. Currently this driver assumes you are using `kops` to build a debian jesse cluster.
c) These are currently unsupported, but I would be keen to merge PRs to which adds all the config options.

**Comment by k0105** [comment]
Thank you very much for your answer.

About (a): A bucket is the AWS S3 folder you want to mount. There could be multiple ones and you always need to specify it as first argument in the `s3fs` or `goofys` mount command. Thus, without specifying a bucket name we cannot mount anything.

About (b): Minikube uses a generated embedded Linux based on Buildroot, cmp. https://buildroot.org/ Here are some basic properties:
```$ cat /proc/version
Linux version 4.9.64 (jenkins@jenkins) (gcc version 7.2.0 (Buildroot 2017.11) ) #1 SMP Tue Jan 23 23:15:00 UTC 2018
$ cat /etc/issue
Welcome to minikube
$ cat /etc/os-release
NAME=Buildroot
VERSION=2017.11
ID=buildroot
VERSION_ID=2017.11
PRETTY_NAME="Buildroot 2017.11"
$ uname -r
4.9.64
```
About (c): If you could just expose the endpoint parameter, i.e. some way to specify `--endpoint=<some_url>` in the mount command (that should look like this: `goofys --endpoint=<some_url> <bucket_name> <mount_target_directory>`) that would immediately allow you to use a lot of other S3 providers besides AWS which would be great both for you and other users. You should be able to do it with close to no additional effort when exposing the bucket_name parameter and credentials and then have a very generic driver that protects you against any vendor lock-in.

**Comment by jacobtomlinson** [comment]
a) In pysssix the bucket is irrelevant, you can access any bucket that your credentials have permission to access. In goofys you must specify the bucket as a configuration option. See the [usage examples](https://github.com/met-office-lab/s3-fuse-flex-volume#usage-examples) for more information.

b) That could potentially prove problematic. We need to be able to detect the OS and then install fuse, pysssix and goofys on that OS.

c) Yes I agree this would be a good option to add.
