### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by koehn** [informatics-lab/s3-fuse-flex-volume#6]
I installed the daemonset, and verified that the `install-host-deps` logs ran successfully on my Debian-9 nodes. So far, so good.

But it doesn't look as though my mount is working correctly and I can't tell why. It looks as though you're passing the `--access-key` and `--secret-key` command line arguments when you invoke `goofys`, but from what I can see those aren't valid arguments; `goofys` expects the access key and secret key to be in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY_ID` environment variables, respectively. I'm not sure how to get at the logs that the driver is generating to see what's happening. 

Thanks for the cool software! I look forward to using it once I get it working!

**Comment by jacobtomlinson** [comment]
Thanks for raiding this.

It is my understanding that `goofys` will take either method of passing in keys. This functionality was added by @flrossetto so perhaps he can comment.

In terms of logging I would recommend checking the kubelet logs and also you could ssh onto the kubernetes host and interact with the driver directly (it should be at `/flexmnt/informaticslab~goofys-flex-volume/goofys-flex-volume). It takes two agruments, the command (`mount` or `unmount`) followed by a json string of the arguments.

**Comment by koehn** [comment]
I've [patched the code](https://github.com/koehn/s3-fuse-flex-volume/) and installed the new `goofys-flex-volume` on my nodes. 

I'm still not getting a successful mount; can I ask what the `subPath` is meant to do? In the README it lists a prototype value of `key/prefix`; what does that refer to? I'm wondering if I configured something incorrectly.

**Comment by jacobtomlinson** [comment]
Awesome! Please feel free to raise a PR with your patch.

`subPath` is to set a lower mount point on the bucket. For example if you set a subpath of `foo/` when all objects begging with `foo/` will be mounted at the root of your mount. This is useful for mounting a "subdirectory" of your bucket.

**Comment by koehn** [comment]
PR raised!

**Comment by koehn** [comment]
Thanks for accepting my PR. Could you push a new Docker image that contains it? Otherwise the helm chart will still have the image with the old driver in it.

**Comment by jacobtomlinson** [comment]
👍 builds should be triggered automatically on Docker Hub but it looks like something went wong. I've manually triggered and it is building now.
